[mypy]
python_version = 3.14
pretty = True
show_error_codes = True
warn_unused_configs = True
explicit_package_bases = True
follow_imports = skip

files = custom_components/ha_inspector

strict = True

[mypy-homeassistant.*]
ignore_missing_imports = True